### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by Bessonov** [BjornTheProgrammer/bun-plugin-html#1]
Hey @BjornTheProgrammer,

thanks for the plugin! I'm not a bun user yet, but I tried out your plugin. I discovered that only some parameters are passed:

https://github.com/BjornTheProgrammer/bun-plugin-html/blob/c0777de1024de55243dca7283b8bffcf185798a0/src/index.ts#L177-L182

In my case, `minify` is missing. Does it make more sense to invert the logic and just remove `entrypoints` and pass everything else as is?

**Comment by BjornTheProgrammer** [comment]
Thanks for leaving your issue! I'm working on a minification process for the `html`, `css`, and `js`. It still needs some refining and testing, but I'll let you know when I implement it fully. Expect a release in the next few days with the update.

**Comment by Bessonov** [comment]
To be honest, HTML minification doesn't play a significant role for me because I mainly develop SPAs. Since this is an HTML plugin, I would prefer that `css` and `js` aren't handled by it but are passed to `bun`, as it is currently done. `bun` already supports [minification](https://bun.sh/docs/bundler#minify), and if I simply add `minify: build.config.minify` between the lines above, it works.

**Comment by BjornTheProgrammer** [comment]
Yes, the minification parameter is now passed to Bun, but my plugin will inline the built `js` and the `css`, then minify the `html`. If you want to try the new version out, I just committed the new code which does this.

Here is the relevant section
```ts
const response = await Bun.build({
	entrypoints: [file.path],
	minify: build.config.minify,
	sourcemap: build.config.sourcemap,
	outdir: path.resolve(process.cwd(), build.config.outdir!),
	root: file.path.split('/').slice(0, root + 1).join('/'),
	naming: '[dir]/[name].[ext]',
})

if (build.config.minify) {
	const scriptRef = convertSrcAttribute(file.ref);
	const scriptElement = document.querySelector(`script[src='${scriptRef}']`)
	if (!response.outputs?.length) {


	const fileText = (document.toString()).replace(/\t/g, '    ');
		const search = `src="${scriptRef}"`;
		const line = returnLineNumberOfOccurance(fileText, search);
		const columnNumber = getColumnNumber(fileText, fileText.indexOf(search) + search.length / 2) + `${line}`.length + 1;
		console.log(getLines(fileText, 4, line + 1));
		console.log('^'.padStart(columnNumber))
		console.error(`HTMLParseError: Specified <script> src '${scriptRef}' failed to build`)
		console.log(`      at ${entrypoint}:${line}:${columnNumber}`)
		continue;
	}
	scriptElement!.removeAttribute('src')
	const scriptFile = Bun.file(response.outputs[0].path);
	scriptElement!.innerHTML = await scriptFile.text();
	fs.unlinkSync(response.outputs[0].path);
	fs.readdirSync(path.dirname(response.outputs[0].path))
}
```

Let me know if this meets your use case!

**Comment by Bessonov** [comment]
I am not sure why you want inline resources. This way, you lose the HTTP caching ability. In addition, you will run into issues with `naming` later.

I am still thinking that you're trying to do too much.

**Comment by BjornTheProgrammer** [comment]
Good point. I'll make it so that inlining will be a separate option.

**Comment by BjornTheProgrammer** [comment]
@Bessonov, I just published a new version that no longer has inlining by default, and is also optional.

**Comment by Bessonov** [comment]
I am pretty sure that it will lead to issues, but it is not my project :+1: Thank you!
