### ISSUE TITLE
Importing from modules

### ISSUE THREAD

**Issue by mewkon** [BjornTheProgrammer/bun-plugin-html#12]
Importing a module from NPM, throws an error.
Minimum reproducible example:

```html
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="@radix-ui/themes/style.css">
        <script src="index.tsx" defer></script>
    </head>
    <body></body>
</html>
``` 

```ts
import html from 'bun-plugin-html'

await Bun.build({
    entrypoints: ['./src/index.html'],
    outdir: './dist',
    minify: true,
    plugins: [
        html()
    ]
});
```

which throws:
```
HTMLParseError: Specified <LINK> href '@radix-ui/themes/style.css' does not exist!
```

I would expect this to work, but it seems that it doesn't.

**Comment by BjornTheProgrammer** [comment]
You should be able to import from node_modules like this...
```html
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="../node_modules/@radix-ui/themes/styles.css">
        <script src="index.tsx" defer></script>
    </head>
    <body></body>
</html>
```

**Comment by mewkon** [comment]
Doing this works, however it places the outputs into two directories `src` and `node_modules` within the build outputs. That may be acceptable but not for all use cases. I think ideally it would be configurable, and maybe hash asset naming could solve the issue of where to place outputs. But either way, I'm closing this as I ended up using esbuild, and I don't believe it's a killer issue.
