### ISSUE TITLE
Browser Requests Incorrect Path for JavaScript File After Build

### ISSUE THREAD

**Issue by RedToxyl** [BjornTheProgrammer/bun-plugin-html#14]
I have the following file structure:
```
.
└── src/
    └── index.html
    └── main.ts
```

In my index.html, I try to use `<script type="module" src="./main.ts"></script>`.
When building it with your provided example script, main.ts and index.html get correctly converted, however now the browser tries to reach url/main.js which doesn't exist, instead of url/dist/main.js.

Trying to set a `<base href="/dist/">` in index.html doesn't work, as now the HTMLParsers looks for ./src/dist/, which obviously doesn't exist. Neither does requesting `<src="../src/main.ts"`. Maybe the tool could change occurrences of entry point to outdir/entrypoint?

I presume this is my own misunderstanding, but I'd be very grateful if you could take the time and run me through how to do this properly :)

**Comment by BjornTheProgrammer** [comment]
Thank you for the bug report! Sorry for not getting to you sooner.

I cannot reproduce this as of `v2.1.0`, maybe that fixed this? It was a complete rewrite. Used the following setup to attempt to reproduce this.

## src/index.html
```html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello World!</title>
    </head>
    <body>
        <h1>Hello World</h1>
        <script type="module" src="./main.ts"></script>
    </body>
</html>
```

## src/main.ts
```ts
console.log('hello world!');
```

## build.ts
```ts
import html from 'bun-plugin-html'
import { $ } from 'bun'

await $`rm -rf ./dist`

await Bun.build({
    entrypoints: ['src/index.html'],
    outdir: 'dist',
    plugins: [html()]
})
```

## index.ts
```ts
Bun.serve({
    fetch(req) {
        const filePath = './dist' + new URL(req.url).pathname;
        const file = Bun.file(filePath);
        return new Response(file);
    },
    error() {
        return new Response(null, { status: 404 });
    },
    port: 3000
})
```
