### ISSUE TITLE
splitting output scripts' order issue in html

### ISSUE THREAD

**Issue by mindon** [BjornTheProgrammer/bun-plugin-html#15]
build.ts

```
import html from "bun-plugin-html";

await Bun.build({
  entrypoints: ["./index.html"],
  outdir: "./out",
  root: ".",
  naming: {
    // default values
    entry: "[dir]/[name].[ext]",
    chunk: "[dir]/[name]-[hash].[ext]",
    asset: "[dir]/[name]-[hash].[ext]",
  },
  plugins: [
    html(),
  ],
  splitting: true,
});

```

input
```
    <script src="a.ts"></script>
    <script src="b/c.ts"></script>
    <script src="b/d.ts"></script>
```

result
```
    <script src="./b/c-y944y4y3.js"></script>
    <script src="./b/d-g6std08f.js"></script>
    <script src="./a-e05yzwsk.js"></script>
```

here's the demo
[demo.zip](https://github.com/user-attachments/files/17657911/demo.zip)

**Comment by mindon** [comment]
> I'm purposely changed the scripts to be chunks, because they technically are chunks from the perspective of the html file. I can make it so that they are treated as entry points instead. Maybe add an additional option to do so?
> 
> What do you think makes most sense?

chunks works great. the only issue is that: the original order is **a->c->d** in html script tags, but output is  **c->d->a**

**Comment by mindon** [comment]
> Should be fixed in v2.1.4! Thank you for the bug report!

it seems the **splitting: true** not working properly in v2.1.4

**Comment by BjornTheProgrammer** [comment]
Let me look into that, thanks for the pull request, I'll merge it shortly!

**Comment by BjornTheProgrammer** [comment]
`v2.1.5` should now fix this issue! Thank you so much for your contributions.

If you have any other issues, please let me know!
