### ISSUE TITLE
How to bundle IMG tag assets?

### ISSUE THREAD

**Issue by alex-knyaz** [BjornTheProgrammer/bun-plugin-html#2]
Hi. I'm not sure if I'm doing something wrong, but I can't quite get how do I suppose to bundle static assets in bun?

I'm trying to include images folder in ./dist, but this works only for LINK tags, not for IMG tags.

**Comment by BjornTheProgrammer** [comment]
Great point. I didn't think to implement file bundling for things other than stylesheets and JavaScript, but will also do so now for `<video>`, `<img>`, `<source>`, `<a>`, `<audio>`, `<embed>`, `<track>`, `<object>`, and `<iframe>`. Expect to see a release in 24 hours which fixes images in particular. Sorry about the inconvenience.

**Comment by alex-knyaz** [comment]
Oh, thanks so much, you are so fast.
