### ISSUE TITLE
css @import rule not being handled

### ISSUE THREAD

**Issue by ScarlyWarly** [BjornTheProgrammer/bun-plugin-html#23]
When attempting to bundle the following html entrypoint, the `@import url(...)` in the css does not get bundled. When bundling the entrypoint without the plugin using bun's experimental css bundling the file is bundled correctly.

The following error is returned when minification is enabled: `Ignoring local @import of "import.css" as resource is missing. 0 [ "Ignoring local @import of \"import.css\" as resource is missing." ]`

```
// index.ts
import html from 'bun-plugin-html'

Bun.build({
    entrypoints: ['./src/index.html'],
    outdir: './public',
    experimentalCss: true,
    plugins: [html({
        inline: true
    })]
})
```

```
// src/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link rel="stylesheet" href="./main.css">
</head>
<body>
    <p></p>
    <script type="module" src="./script.ts"></script>
</body>
</html>
```

```
// src/main.css
@import url('./import.css');

* {
    border-color: red;
}
```

```
// src/import.css
html {
    background-color: black;
    color: white;
}
```

**Comment by BjornTheProgrammer** [comment]
This is because `bun-plugin-html` doesn't use Bun to bundle CSS files. I considered doing so using the experimental CSS feature, but I wanted to wait until it was stable. I could add the CSS files to the bundler if this feature is on though. I'm probably going to rewrite major sections of the code though, since the plugin does need a refactor.

**Comment by mindon** [comment]
one more case on css minify, it's styles of lit <https://lit.dev/docs/components/styles/> 
such contents with specified rules inside a js
```js
  static styles = css`
    p {
      color: green;
    }
  `;
```
