### ISSUE TITLE
Errror while bundling html with typescript code

### ISSUE THREAD

**Issue by gtrabanco** [BjornTheProgrammer/bun-plugin-html#3]
I am having issues when bundling, it does not bundle the js code:

```
error: onLoad plugins must return an object with "contents" as a string or Uint8Array
~/handball-liveshow-spain/src/graphics/live.html:1:0
```

Here is my build file: https://github.com/BalonmanoVetusta/handball-liveshow-spain/blob/a97dedf74609a19527b0551e80bade9274878792/bin/build.js

To test this in your local:

```shell
git clone https://github.com/BalonmanoVetusta/handball-liveshow-spain
cd handball-liveshow-spain
git checkout auto_goals
bun install
bun run build
```

You should see 3 builded directories:
- extension - which is build with esbuild because I needed in commonjs
- dashboard - src/dashboard
- graphics - src/graphics

It build fine the css but not the js after I have deleted parcel from dependencies. You can test full build with:

```shell
git checkout dev
npm install # Some different dependencies
npm run build:clean && npm run build
```

I am sure in dev branch is building because some non deleted old configuration.

**Comment by BjornTheProgrammer** [comment]
@gtrabanco, thanks for your bug report. This has now been fixed with the latest release of v1.3.1. The issue was that if only a single path was provided it would not return the directory, but instead just the file for the root path. Let me know if this works for you.
