### ISSUE TITLE
[Issue] onLoad plugins must return an object with "contents"

### ISSUE THREAD

**Issue by gtrabanco** [BjornTheProgrammer/bun-plugin-html#6]
![Captura de Pantalla 2023-11-25 a las 16 19 08](https://github.com/BjornTheProgrammer/bun-plugin-html/assets/1969593/eaa4182b-8c81-47b9-854a-c25eb1de792d)

The code to build is here: https://github.com/BalonmanoVetusta/handball-liveshow-spain/blob/fix_build/bin/build.js

I am receiving this error while building with:

Bun: `1.0.14+93714292b`
bun-plugin-html: `1.3.2`

**Comment by BjornTheProgrammer** [comment]
@gtrabanco I've fixed the path resolution issue with release v1.3.3, however as for the return values of Bun.build, that will be much harder. 

Currently, I've gotten it to semi-work by making outdir undefined and changing all the entrypoints to be the new generated files, however, there are plenty of issues with this approach, which involves the response object lying to the user, which seems to be much worse behavior.

I've investigated the source code of multiple other plugins, looked at the bun source code, and reread the docs, however at this point it doesn't seem like it is possible to just output any file you want (even with the 'file' loader it breaks when supplied an html file).

What would your opinion be of adding this disclaimer, while more alternatives are explored in the future?

<img width="528" alt="Screenshot 2023-11-28 at 5 55 27 PM" src="https://github.com/BjornTheProgrammer/bun-plugin-html/assets/75190918/7cfd31ce-4fd1-4607-8895-2519d4799677">

**Comment by BjornTheProgrammer** [comment]
Thanks for leaving a reply @gtrabanco. I pushed a patch for this a few days ago. Try upgrading to v1.3.3, it should work with this version, and have the correctly generated name for the html file. 

Also I'm not opposed to the idea of giving the output if I could see a valid use case for this behavior, since there are some trade offs.

**Comment by BjornTheProgrammer** [comment]
Weird, the current package.json shows v1.3.2.

<img width="328" alt="Screenshot 2023-12-01 at 9 43 52 AM" src="https://github.com/BjornTheProgrammer/bun-plugin-html/assets/75190918/45bec96e-aa5e-43e8-ae10-346c3e3f4142">

When I upgrade to v1.3.3, and run the build code the html seems to generate fine
<img width="168" alt="Screenshot 2023-12-01 at 9 51 46 AM" src="https://github.com/BjornTheProgrammer/bun-plugin-html/assets/75190918/94501803-7391-4742-8482-fc6df9e833dd">

**Comment by BjornTheProgrammer** [comment]
Lmao @gtrabanco, I know that it can be confusing due to how `npm install` and `bun install` so I don't mind. Once again thanks for the bug report! I'll keep looking for a solution to the output issue in the future.
